# Generated by Django 2.2 on 2020-01-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Genre',
            new_name='genre',
        ),
    ]
