# Generated by Django 2.2 on 2020-01-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
